In [ ]:
================================= EDA ======================================================
1) Pandas      : DataFrame or data applications
2) numpy       : Numerical python for math operations
3) matplotlib  : For plots, graphs    
4) Seaborn     : For plots, graphs
5) Bokhe       : For plots
6) Plotly      : For plots

============================Machine Learning========================

7) Scikit learn(Sklearn)   : ML Models
8) stats                   : statistical models
    
========================Data retrieval from sql scrapping==============
9) sqlite              : connect with database
10) Beautiful soap     : scrap the data from website
11) websocket          : scrap
    
========================= Deep Learning/ Computer Vision ===========================
12) Tensorflow         : Google
13) Keras              : DL models
14) OpenCV             : Image Operations
15) Pillow (PIL)       : Image Operations
16) Pytorch            : Facebook
17) Pretrained models:
    VGG16
    Mobilenet
    RESNET
    RCNN
    MASKRCNN
    FASTERCNN
    YOLO
    
=============================== Natural Language Process =================
18) NLTK          :    Natural Language Process
19) Scipy         
20) Word2vec (How words are converted into Vector) : 
21) GloVE
22) Wordcloud


=========================== Hugging Face =========================
23) Transformers           : BERT(Bidirectional Encoder Representations from Transformer)

============================ GenAI models ==========================
24) OpenAI+Microsoft       : GPT Models
25) Google                 : Gemini
26) Amazon                 : Q
27) Meta Facebook          : MetaAI
28) Apple


LLAMA
GEMMA
Dalle.E
TS


ALL ARE HAVING DIFFERENT PACKAGES

====================== LANGCHAIN ====================================
# All the GenAI models use LANGCHAIN Framework
29) Langchain Framework
======================= Deployements =========================
30) Flask
31) Streamlit
32) Django

======================== Mlops ============================
33) MLflow
34) Kubeflow
35) Azure AI services
36) GCP : GCP packages

**Step 1** 
**Create a dataframe**

- we will create dataframe using list

- we will create dataframe using dictionary

In [3]:
import pandas as pd

In [5]:
d1= pd.DataFrame()
d1

Empty DataFrame
Columns: []
Index: []

In [6]:
type(d1)

pandas.core.frame.DataFrame

**Step-2**

**Provide the data**

In [7]:
names = ['tarun','surender','mohith']
pd.DataFrame(names)

0
0     tarun
1  surender
2    mohith

In [8]:
names = ['tarun','surender','mohith']
age = [20,21,22]
data = zip(names,age)
pd.DataFrame(data)

0   1
0     tarun  20
1  surender  21
2    mohith  22

In [9]:
names = ['tarun','surender','mohith']
age = [20,21,22]
city = ['Hyd','Blr','ECIL']
data = zip(names,age,city)
pd.DataFrame(data)

0   1     2
0     tarun  20   Hyd
1  surender  21   Blr
2    mohith  22  ECIL

**Step-3**
**Provide the column names**

In [10]:
pd.DataFrame(names,
             columns=['Names'])

Names
0     tarun
1  surender
2    mohith

In [11]:
names = ['tarun','surender','mohith']
age = [20,21,22]
city = ['Hyd','Blr','ECIL']
data = zip(names,age,city)
cols = ['Names', 'Age','City']
pd.DataFrame(data, columns=cols)

Names  Age  City
0     tarun   20   Hyd
1  surender   21   Blr
2    mohith   22  ECIL

**Step-4**

**Providing index**

In [13]:
names = ['tarun','surender','mohith']
age = [20,21,22]
city = ['Hyd','Blr','ECIL']

data = zip(names,age,city)
ix = ['A','B','C'] # 3 rows we need 3 index
cols = ['Names', 'Age','City'] # 3 columns, 3 Values


pd.DataFrame(data, 
             index=ix, 
             columns=cols)

Names  Age  City
A     tarun   20   Hyd
B  surender   21   Blr
C    mohith   22  ECIL

In [16]:
names = ['tarun','surender','mohith']
age = [20,21,22]
city = ['Hyd','Blr','ECIL']
data = zip(names,age)

column=['Name', 'Age']
df = pd.DataFrame(data, index=city,columns=column)

In [17]:
df

Name  Age
Hyd      tarun   20
Blr   surender   21
ECIL    mohith   22

In [ ]:
# tomorrow Python MCQ 
# 50 Questions 
# 10:30 to 12:30

In [ ]:
# create a dataframe

# provide the data 

# add the columns 

# provide the column names

# provide the index

**Step-5**


**Add a new column on existing dataframe**

In [5]:
# Create a Dataframe with name, age and city

names = ['Rahul','Gautham','Rizwana']
age = [20,21,22]
city = ['Hyd','Blr','Chennai']
data = zip(names,age,city)
cols = ['Names', 'Age','City']
df = pd.DataFrame(data, columns=cols)
df

Names  Age     City
0    Rahul   20      Hyd
1  Gautham   21      Blr
2  Rizwana   22  Chennai

In [ ]:
- If you want to add a new column first check how many rows are there

- For ex in above dataframe we have 3 rows

- Your new column also should have 3 rows

- Suppose i want to create a new column called salary

- Make a list of salary with 3 values 

- salary= [100000,200000,300000]

**Syntax**: dataframe[column] =list of values
    
-  salary= [100000,200000,300000]

- df['salary'] = salary

In [6]:
salary = [100000,200000,300000]
df['Salary'] = salary
df

Names  Age     City  Salary
0    Rahul   20      Hyd  100000
1  Gautham   21      Blr  200000
2  Rizwana   22  Chennai  300000

**Use Case-1**

- Create a empty dataframe first

- create 3 lists using list comprehension

- Here list 1 should have 1 to 10 values 

- list 2 should have square of 1 to 10

- list3 should have cube of 1 to 10

- Finally make a dataframe 

In [11]:
df1 = pd.DataFrame()
df1

Empty DataFrame
Columns: []
Index: []

In [12]:
list1 = [i for i in range(1,10)]
list2 = [i*i for i in range(1,10)]
list3 = [i*i*i for i in range(1,10)]

df1['X'] = list1
df1['Y'] = list2
df1['Z'] = list3
df1

X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125
5  6  36  216
6  7  49  343
7  8  64  512
8  9  81  729

**Step-6**

- Update the already existed column

- Create a new column 

    - Creating a new list 
    
    - df['S']
    
    - Creating  a new column the column name is our choice
    

- Update the existing column are same way only

- while upadting the existing oclumn we need to provide already  existed column name only

- Here also we need to make a list of values that is equal to no. of rows

**Syntax**

- df['Z'] = list of values

In [15]:
# Creating new list and update in the Z

# dataframe: df1
# which column you want to update : Z (Column name)

z = [i**4 for i in range(1,10)]

df1['Z'] = z
df1

X   Y     Z
0  1   1     1
1  2   4    16
2  3   9    81
3  4  16   256
4  5  25   625
5  6  36  1296
6  7  49  2401
7  8  64  4096
8  9  81  6561

**Step-7**

- How to drop a column

In [16]:
# how to check the no of columns

df1.columns

Index(['X', 'Y', 'Z'], dtype='object')

- If you want to drop a specific column we will use drop method

- we already know about diffrence b/w keywords and methods

- Keywords will use directly 

- Methods will use with corresponding dataFrame

- Here methodname is drop

**df1.drop()**

- column which one you want to provide 

- Axis represents the specified value is a row or column

    - Axis 0 means rows
    
    - By default axis is 0
    
    
    - Axis1 means column
    
    
-  inplace will provide overwrite dataframe or not

- so inplace= true indicates overwrite the dataframe

- inplace = false indicates the modified dataframe will be used when you provide new variable for the operation

In [17]:
df1.drop(['Zs'],axis=1,inplace=True)

In [22]:
df1

X   Y
0  1   1
1  2   4
2  3   9
3  4  16
4  5  25
5  6  36
6  7  49
7  8  64
8  9  81

In [ ]:
drop , axis , inplace 

In [ ]:
# REad the datframe
# provide the data
# provide the column names
# change the index
# add the new column
# modify the existing the column
# drop the column
# axis in place 
# you need to create a new column
# drop the old column

**Step-8**

**Drop the row**

- Drop the row and column , both are similar , 

- The only difference is axis 

- Axis 0 represents rows

- By default axis is 0

- which means if we provide any value it will represent rows only

In [3]:
# Data Frame name: df2
import pandas as pd
df2 = pd.DataFrame()
list1 = [i for i in range(1,10)]
list2 = [i*i for i in range(1,10)]
list3 = [i*i*i for i in range(1,10)]

df2['Number'] = list1
df2['Square'] = list2
df2['Cube'] = list3
df2

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
4       5      25   125
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [4]:
df2.drop(4)

# if we run this we will get error
# by default axis is 0 which represents about rows
# but Number is a column
# if you want to drop row then provide the row index

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512
8       9      81   729

In [5]:
# Myltiple rows 
# Multiple columns keep always in a list

df2.drop([4,8])

Number  Square  Cube
0       1       1     1
1       2       4     8
2       3       9    27
3       4      16    64
5       6      36   216
6       7      49   343
7       8      64   512

In [7]:
df2.drop([0,1], axis=1)

# [0,1] ---> rows

# axis=1 ---> columns

# error

KeyError: '[0, 1] not found in axis'

In [8]:
df2.columns[[0,1]]

Index(['Number', 'Square'], dtype='object')

**Step-9**

**How to select the column**

In [14]:
df2['Number']

# Series type
# No column name is displayed
# Whenever you see this type: Series type

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

In [18]:
type(df2['Number'])

pandas.core.series.Series

In [16]:
df2[['Square']]

#Data Frame Type

Square
0       1
1       4
2       9
3      16
4      25
5      36
6      49
7      64
8      81

In [19]:
type(df2[['Number']])

pandas.core.frame.DataFrame

In [20]:
df2.Number

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
Name: Number, dtype: int64

In [21]:
type(df2.Number)

pandas.core.series.Series

- df2['Number']: Series Type
    
- df2[['Number']]: DataFrame type
    
- df2.Number: Series Type

In [23]:
cols = ['Number','Square']
df2[cols]

Number  Square
0       1       1
1       2       4
2       3       9
3       4      16
4       5      25
5       6      36
6       7      49
7       8      64
8       9      81

In [24]:
df2['Number'].values

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [ ]:
# All values comes in an array

# Array means it is a list of elements only represented using numpy package

# Generally elements present in 4 ways 
#  i. List: Basic representations
    
#  ii. Numpy Array: Array with Numpy package

#  iii. Tensors: Tensorflow package 
    
#   Iv. Torch: Pytorch package

In [26]:
list1=[1,2,3,4]
list1

[1, 2, 3, 4]

In [27]:
import numpy as np
np.array(list1)

array([1, 2, 3, 4])

In [29]:
list1 = [1,2,3,4]
list2=[10,20,30,40]
list1+list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [31]:
l1=np.array(list1)
l2=np.array(list2)
l1+l2

array([11, 22, 33, 44])

In [ ]:
# 3 days everyday one numpy
# a new package in the market : numpy
# you know python
# ru able to learn or not

In [ ]:
# azure , gcp, aws

In [32]:
df2['Number'].values
# Imagine we worked on an ML problem
# we got some series of values 
# With that series of values also we can create a data Frame

array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [33]:
df2['NUMBER'] = df2['Number'].values
df2

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

**Step-10**

**Save the DataFrame**

- dataframes we can save in 2 formats:

    - csv: Comma Separated Value
    
    - xlsx: Excel Format
    
- In order to save any data

    - Where you want to save: directory name
    
    - What is the name of the file for storing
    
    - What is the extension
    
- We already seen same in the file handling session

**Case-1**

- Saving the file at same location

- No need to provide directory path

- Directly give only name of the file and extension

In [35]:
# datframe name: df2

df2.to_csv('Data1.csv')
df2.to_excel('Data1.xlsx')

**Step-11**

**How to read a DataFrame**

In [36]:
import pandas as pd
pd.read_csv('Data1.csv')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

In [37]:
import os 
os.getcwd()

'C:\\Users\\Rahul\\Documents\\NareshIT\\EDA'

In [38]:
pd.read_excel('Data1.xlsx')

Unnamed: 0  Number  Square  Cube  NUMBER
0           0       1       1     1       1
1           1       2       4     8       2
2           2       3       9    27       3
3           3       4      16    64       4
4           4       5      25   125       5
5           5       6      36   216       6
6           6       7      49   343       7
7           7       8      64   512       8
8           8       9      81   729       9

**Step-13**

**How to avoid index column**

- While we save the dataframe 

- Automatically a new column will be created 

- that we need to avoid

- Permission denied means close the data file from laptop

In [41]:
# dataframe name: df2
# save the data without index column
df2.to_csv('Data1.csv', index=False )
df2.to_excel('Data1.xlsx',index=False)

In [47]:
# read the data
import pandas as pd
pd.read_csv('Data1.csv')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9

In [46]:
pd.read_excel('Data1.xlsx')

Number  Square  Cube  NUMBER
0       1       1     1       1
1       2       4     8       2
2       3       9    27       3
3       4      16    64       4
4       5      25   125       5
5       6      36   216       6
6       7      49   343       7
7       8      64   512       8
8       9      81   729       9